from sqlalchemy import Column, String, DateTime, Enum, ForeignKey, Integer, JSON, Text
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
import enum
from app.database import Base



class ProjectStatus(str, enum.Enum):
    """Project analysis status."""
    CREATED = "created"
    UPLOADING = "uploading"
    UPLOADED = "uploaded"
    PROCESSING = "processing"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


class SourceType(str, enum.Enum):
    """Source type for the project."""
    ZIP_UPLOAD = "zip_upload"
    GITHUB_URL = "github_url"


class PersonaType(str, enum.Enum):
    """Documentation persona types."""
    SDE = "sde"
    PM = "pm"


class Project(Base):
    """Project model for code analysis tracking."""

    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False)
    description = Column(Text)

    # Ownership
    owner_id = Column(String, ForeignKey("users.id"), nullable=False)
    owner = relationship("User", back_populates="projects")

    # Source Information
    source_type = Column(Enum(SourceType), nullable=False)
    source_url = Column(String)  # GitHub URL if applicable
    file_path = Column(String)  # Local storage path
    file_size = Column(Integer)  # Size in bytes

    # Analysis Configuration
    personas = Column(JSON, nullable=False)  # List of persona types ["sde", "pm"]

    # Status Tracking
    status = Column(Enum(ProjectStatus), default=ProjectStatus.CREATED)
    progress_percentage = Column(Integer, default=0)
    error_message = Column(Text)

    # Metadata
    repository_metadata_json = Column(JSON)  # Detected languages, frameworks, etc.

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime)

    # Code Generated by Sidekick is for learning and experimentation purposes only.

    # Add to Project model:
    repository_metadata = relationship("RepositoryMetadata", back_populates="project", lazy="noload", uselist=False)
    file_metadata = relationship("FileMetadata", back_populates="project", lazy="noload")
    code_chunks = relationship("CodeChunk", back_populates="project", lazy="noload")
    progress = relationship("ProjectProgress", back_populates="project", uselist=False)
    config = relationship("AnalysisConfig", back_populates="project", uselist=False, cascade="all, delete-orphan")
